name: tada-dip
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - git
  - jupyter
  - notebook
  - pytest
  - ipykernel
  - imageio
  - matplotlib
  - cmake
  - make

  - pip:
    - -e .
    - torch
    - torchvision
    - lightning
    - jsonargparse[signatures]
    - pydicom